### ISSUE TITLE
arm64-darwin  build actually creates x86_64   shared library

### ISSUE THREAD

**Issue by maxirmx** [fontist/ffi-libarchive-binary#16]
The test  shows that arm64-darwin  build actually creates x86_64   shared library

https://github.com/fontist/ffi-libarchive-binary/actions/runs/3260985780/jobs/5355105770

```
          - os: macos-latest
            platform: arm64-darwin
            ruby: '2.7'
```

```
Invalid file format '/Users/runner/work/ffi-libarchive-binary/ffi-libarchive-binary/lib/ffi-libarchive-binary/libarchive.dylib: Mach-O 64-bit dynamically linked shared library x86_64', 'Mach-O 64-bit dynamically linked shared library arm64' expected
```

**Comment by ronaldtse** [comment]
I'm a bit confused -- GitHub Actions does not have the arm64-darwin platform. Building for arm requires usage of Docker's buildx?
